set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN N5} [get_ports rst]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN E3} [get_ports clk_100MHz]

set_property IOSTANDARD LVCMOS33 [get_ports SW]
set_property PACKAGE_PIN T8 [get_ports {SW[31]}]
set_property PACKAGE_PIN U1 [get_ports {SW[30]}]
set_property PACKAGE_PIN U2 [get_ports {SW[29]}]
set_property PACKAGE_PIN U3 [get_ports {SW[28]}]
set_property PACKAGE_PIN V5 [get_ports {SW[27]}]
set_property PACKAGE_PIN V6 [get_ports {SW[26]}]
set_property PACKAGE_PIN V7 [get_ports {SW[25]}]
set_property PACKAGE_PIN V9 [get_ports {SW[24]}]
set_property PACKAGE_PIN V11 [get_ports {SW[23]}]
set_property PACKAGE_PIN V12 [get_ports {SW[22]}]
set_property PACKAGE_PIN U14 [get_ports {SW[21]}]
set_property PACKAGE_PIN V15 [get_ports {SW[20]}]
set_property PACKAGE_PIN V16 [get_ports {SW[19]}]
set_property PACKAGE_PIN V17 [get_ports {SW[18]}]
set_property PACKAGE_PIN R18 [get_ports {SW[17]}]
set_property PACKAGE_PIN P18 [get_ports {SW[16]}]
set_property PACKAGE_PIN R8 [get_ports {SW[15]}]
set_property PACKAGE_PIN T9 [get_ports {SW[14]}]
set_property PACKAGE_PIN V1 [get_ports {SW[13]}]
set_property PACKAGE_PIN V2 [get_ports {SW[12]}]
set_property PACKAGE_PIN V4 [get_ports {SW[11]}]
set_property PACKAGE_PIN U6 [get_ports {SW[10]}]
set_property PACKAGE_PIN U7 [get_ports {SW[9]}]
set_property PACKAGE_PIN U9 [get_ports {SW[8]}]
set_property PACKAGE_PIN U11 [get_ports {SW[7]}]
set_property PACKAGE_PIN U12 [get_ports {SW[6]}]
set_property PACKAGE_PIN U13 [get_ports {SW[5]}]
set_property PACKAGE_PIN V14 [get_ports {SW[4]}]
set_property PACKAGE_PIN U16 [get_ports {SW[3]}]
set_property PACKAGE_PIN U17 [get_ports {SW[2]}]
set_property PACKAGE_PIN T18 [get_ports {SW[1]}]
set_property PACKAGE_PIN P17 [get_ports {SW[0]}]


set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN T10} [get_ports Sel[1]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN R10} [get_ports Sel[0]]

# 数码管的段选引脚约束
set_property IOSTANDARD LVCMOS33 [get_ports SEG]
set_property PACKAGE_PIN E2 [get_ports {SEG[7]}]
set_property PACKAGE_PIN A3 [get_ports {SEG[6]}]
set_property PACKAGE_PIN B1 [get_ports {SEG[5]}]
set_property PACKAGE_PIN E1 [get_ports {SEG[4]}]
set_property PACKAGE_PIN F1 [get_ports {SEG[3]}]
set_property PACKAGE_PIN D2 [get_ports {SEG[2]}]
set_property PACKAGE_PIN B3 [get_ports {SEG[1]}]
set_property PACKAGE_PIN C1 [get_ports {SEG[0]}]

# 数码管的位选及使能信号的约束
set_property IOSTANDARD LVCMOS33 [get_ports AN]
set_property PACKAGE_PIN G1 [get_ports {AN[7]}]
set_property PACKAGE_PIN B2 [get_ports {AN[6]}]
set_property PACKAGE_PIN A1 [get_ports {AN[5]}]
set_property PACKAGE_PIN B4 [get_ports {AN[4]}]
set_property PACKAGE_PIN A4 [get_ports {AN[3]}]
set_property PACKAGE_PIN A5 [get_ports {AN[2]}]
set_property PACKAGE_PIN B6 [get_ports {AN[1]}]
set_property PACKAGE_PIN A6 [get_ports {AN[0]}]


