set_property SRC_FILE_INFO {cfile:D:/Labs/DCLabs/code/MUX8_1.xdc rfile:../../../../MUX8_1.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN T8} [get_ports H[3]]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN U1} [get_ports H[2]]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN U2} [get_ports H[1]]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN U3} [get_ports H[0]]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V5} [get_ports G[3]]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V6} [get_ports G[2]]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V7} [get_ports G[1]]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V9} [get_ports G[0]]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V11} [get_ports F[3]]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V12} [get_ports F[2]]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN U14} [get_ports F[1]]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V15} [get_ports F[0]]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V16} [get_ports E[3]]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V17} [get_ports E[2]]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN R18} [get_ports E[1]]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P18} [get_ports E[0]]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN R8} [get_ports D[3]]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN T9} [get_ports D[2]]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V1} [get_ports D[1]]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V2} [get_ports D[0]]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V4} [get_ports C[3]]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN U6} [get_ports C[2]]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN U7} [get_ports C[1]]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN U9} [get_ports C[0]]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN U11} [get_ports B[3]]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN U12} [get_ports B[2]]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN U13} [get_ports B[1]]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V14} [get_ports B[0]]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN U16} [get_ports A[3]]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN U17} [get_ports A[2]]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN T18} [get_ports A[1]]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P17} [get_ports A[0]]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN L3} [get_ports Y[3]]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN L4} [get_ports Y[2]]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN M3} [get_ports Y[1]]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN M4} [get_ports Y[0]]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN T10} [get_ports S[2]]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN R10} [get_ports S[1]]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN T11} [get_ports S[0]]
