set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN U17} [get_ports code[2]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN T18} [get_ports code[1]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P17} [get_ports code[0]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V17} [get_ports G1]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN R18} [get_ports G2A]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P18} [get_ports G2B]

set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN L3} [get_ports Y[7]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN L4} [get_ports Y[6]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN M3} [get_ports Y[5]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN M4} [get_ports Y[4]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN N4} [get_ports Y[3]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P3} [get_ports Y[2]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P4} [get_ports Y[1]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN R3} [get_ports Y[0]]